[project]
name = 'Decentralized-Specialized-Disaster-Recovery-Tool-Library'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.case-registration]
path = 'contracts/case-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.expert-matching]
path = 'contracts/expert-matching.clar'
clarity_version = 2
epoch = 2.5

[contracts.knowledge-synthesis]
path = 'contracts/knowledge-synthesis.clar'
clarity_version = 2
epoch = 2.5

[contracts.treatment-outcome]
path = 'contracts/treatment-outcome.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
